from .world_mirror_v1 import NODE_CLASS_MAPPINGS as V1_MAPPINGS
from .world_mirror_v1 import NODE_DISPLAY_NAME_MAPPINGS as V1_DISPLAY_MAPPINGS
from .world_mirror_v2 import NODE_CLASS_MAPPINGS as V2_MAPPINGS
from .world_mirror_v2 import NODE_DISPLAY_NAME_MAPPINGS as V2_DISPLAY_MAPPINGS
from .panorama_mapper import NODE_CLASS_MAPPINGS as PANORAMA_MAPPER_MAPPINGS
from .panorama_mapper import NODE_DISPLAY_NAME_MAPPINGS as PANORAMA_MAPPER_DISPLAY_MAPPINGS
from .world_stereo import NODE_CLASS_MAPPINGS as WS_MAPPINGS
from .world_stereo import NODE_DISPLAY_NAME_MAPPINGS as WS_DISPLAY_MAPPINGS
from .splat_patch_poc import NODE_CLASS_MAPPINGS as SPLAT_PATCH_MAPPINGS
from .splat_patch_poc import NODE_DISPLAY_NAME_MAPPINGS as SPLAT_PATCH_DISPLAY_MAPPINGS
from .worldgen import NODE_CLASS_MAPPINGS as WORLDGEN_MAPPINGS
from .worldgen import NODE_DISPLAY_NAME_MAPPINGS as WORLDGEN_DISPLAY_MAPPINGS
from .hyworld2_native import NODE_CLASS_MAPPINGS as HYWORLD2_NATIVE_MAPPINGS
from .hyworld2_native import NODE_DISPLAY_NAME_MAPPINGS as HYWORLD2_NATIVE_DISPLAY_MAPPINGS
from .qwen_pano import NODE_CLASS_MAPPINGS as QWEN_PANO_MAPPINGS
from .qwen_pano import NODE_DISPLAY_NAME_MAPPINGS as QWEN_PANO_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **V1_MAPPINGS,
    **V2_MAPPINGS,
    **PANORAMA_MAPPER_MAPPINGS,
    **WS_MAPPINGS,
    **SPLAT_PATCH_MAPPINGS,
    **WORLDGEN_MAPPINGS,
    **HYWORLD2_NATIVE_MAPPINGS,
    **QWEN_PANO_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **V1_DISPLAY_MAPPINGS,
    **V2_DISPLAY_MAPPINGS,
    **PANORAMA_MAPPER_DISPLAY_MAPPINGS,
    **WS_DISPLAY_MAPPINGS,
    **SPLAT_PATCH_DISPLAY_MAPPINGS,
    **WORLDGEN_DISPLAY_MAPPINGS,
    **HYWORLD2_NATIVE_DISPLAY_MAPPINGS,
    **QWEN_PANO_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
